name: transformational_ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - datasets
  - pandas
  - matplotlib
  - seaborn
  - pyarrow
  - ipykernel
  - jupyter
  - notebook
  - pip
